# Generated by Django 4.1.2 on 2022-11-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_alter_entry_text_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(),
        ),
    ]
